<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Preceptor’s Primer for Bayesian Data Science - 9&nbsp; Four Parameters</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-five-parameters.html" rel="next">
<link href="./08-three-parameters.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Four Parameters</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Preceptor’s Primer for Bayesian Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/PPBDS/primer/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="" title="Download" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-download"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
<li>
          <a class="dropdown-item sidebar-tools-main-item" href="./Preceptor-s-Primer-for-Bayesian-Data-Science.pdf">
            <i class="bi bi-bi-file-pdf pe-1"></i>
          Download PDF
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="./Preceptor-s-Primer-for-Bayesian-Data-Science.epub">
            <i class="bi bi-bi-journal pe-1"></i>
          Download ePub
          </a>
        </li>
    </ul>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preamble.html" class="sidebar-item-text sidebar-link">Preamble</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-getting-started.html" class="sidebar-item-text sidebar-link">Getting Started</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-visualization.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Visualization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-wrangling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Wrangling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-rubin-causal-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Rubin Causal Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Probability</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-one-parameter.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One Parameter</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-two-parameters.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two Parameters</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-three-parameters.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Three Parameters</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-four-parameters.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Four Parameters</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-five-parameters.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Five Parameters</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-n-parameters.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">N Parameters</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tools.html" class="sidebar-item-text sidebar-link">Tools</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./animation.html" class="sidebar-item-text sidebar-link">Animation</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./set-up.html" class="sidebar-item-text sidebar-link">Set Up for Working on The Primer</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#transforming-variables" id="toc-transforming-variables" class="nav-link active" data-scroll-target="#transforming-variables"> <span class="header-section-number">9.1</span> Transforming variables</a>
  <ul class="collapse">
<li><a href="#centering" id="toc-centering" class="nav-link" data-scroll-target="#centering"> <span class="header-section-number">9.1.1</span> Centering</a></li>
  <li><a href="#scaling" id="toc-scaling" class="nav-link" data-scroll-target="#scaling"> <span class="header-section-number">9.1.2</span> Scaling</a></li>
  <li><a href="#z-scores" id="toc-z-scores" class="nav-link" data-scroll-target="#z-scores"> <span class="header-section-number">9.1.3</span> <em>z</em>-scores</a></li>
  <li><a href="#taking-logs" id="toc-taking-logs" class="nav-link" data-scroll-target="#taking-logs"> <span class="header-section-number">9.1.4</span> Taking logs</a></li>
  <li><a href="#adding-transformed-terms" id="toc-adding-transformed-terms" class="nav-link" data-scroll-target="#adding-transformed-terms"> <span class="header-section-number">9.1.5</span> Adding transformed terms</a></li>
  <li><a href="#transforming-the-outcome-variable" id="toc-transforming-the-outcome-variable" class="nav-link" data-scroll-target="#transforming-the-outcome-variable"> <span class="header-section-number">9.1.6</span> Transforming the outcome variable</a></li>
  <li><a href="#interpreting-coefficients" id="toc-interpreting-coefficients" class="nav-link" data-scroll-target="#interpreting-coefficients"> <span class="header-section-number">9.1.7</span> Interpreting coefficients</a></li>
  </ul>
</li>
  <li>
<a href="#selecting-variables" id="toc-selecting-variables" class="nav-link" data-scroll-target="#selecting-variables"> <span class="header-section-number">9.2</span> Selecting variables</a>
  <ul class="collapse">
<li><a href="#general-guidelines-for-selecting-variables" id="toc-general-guidelines-for-selecting-variables" class="nav-link" data-scroll-target="#general-guidelines-for-selecting-variables"> <span class="header-section-number">9.2.1</span> General guidelines for selecting variables</a></li>
  <li><a href="#variables-in-the-trains-dataset" id="toc-variables-in-the-trains-dataset" class="nav-link" data-scroll-target="#variables-in-the-trains-dataset"> <span class="header-section-number">9.2.2</span> Variables in the <code>trains</code> dataset</a></li>
  <li><a href="#att_end-treatment-att_start" id="toc-att_end-treatment-att_start" class="nav-link" data-scroll-target="#att_end-treatment-att_start"> <span class="header-section-number">9.2.3</span> att_end ~ treatment + att_start</a></li>
  <li><a href="#income-age-liberal" id="toc-income-age-liberal" class="nav-link" data-scroll-target="#income-age-liberal"> <span class="header-section-number">9.2.4</span> income ~ age + liberal</a></li>
  <li><a href="#liberal-iincome1e05-party" id="toc-liberal-iincome1e05-party" class="nav-link" data-scroll-target="#liberal-iincome1e05-party"> <span class="header-section-number">9.2.5</span> liberal ~ I(income/1e+05) + party</a></li>
  <li><a href="#final-thoughts" id="toc-final-thoughts" class="nav-link" data-scroll-target="#final-thoughts"> <span class="header-section-number">9.2.6</span> Final thoughts</a></li>
  </ul>
</li>
  <li>
<a href="#comparing-models-in-theory" id="toc-comparing-models-in-theory" class="nav-link" data-scroll-target="#comparing-models-in-theory"> <span class="header-section-number">9.3</span> Comparing models in theory</a>
  <ul class="collapse">
<li><a href="#better-models-make-better-predictions" id="toc-better-models-make-better-predictions" class="nav-link" data-scroll-target="#better-models-make-better-predictions"> <span class="header-section-number">9.3.1</span> Better models make better predictions</a></li>
  <li><a href="#beware-overfitting" id="toc-beware-overfitting" class="nav-link" data-scroll-target="#beware-overfitting"> <span class="header-section-number">9.3.2</span> Beware overfitting</a></li>
  <li><a href="#better-models-make-better-predictions-on-new-data" id="toc-better-models-make-better-predictions-on-new-data" class="nav-link" data-scroll-target="#better-models-make-better-predictions-on-new-data"> <span class="header-section-number">9.3.3</span> Better models make better predictions on new data</a></li>
  </ul>
</li>
  <li>
<a href="#comparing-models-in-practice" id="toc-comparing-models-in-practice" class="nav-link" data-scroll-target="#comparing-models-in-practice"> <span class="header-section-number">9.4</span> Comparing models in practice</a>
  <ul class="collapse">
<li><a href="#cross-validation-using-loo" id="toc-cross-validation-using-loo" class="nav-link" data-scroll-target="#cross-validation-using-loo"> <span class="header-section-number">9.4.1</span> Cross validation using <code>loo()</code></a></li>
  <li><a href="#comparing-models-using-loo_compare" id="toc-comparing-models-using-loo_compare" class="nav-link" data-scroll-target="#comparing-models-using-loo_compare"> <span class="header-section-number">9.4.2</span> Comparing models using <code>loo_compare()</code></a></li>
  </ul>
</li>
  <li><a href="#testing-is-nonsense" id="toc-testing-is-nonsense" class="nav-link" data-scroll-target="#testing-is-nonsense"> <span class="header-section-number">9.5</span> Testing is nonsense</a></li>
  <li>
<a href="#parallel-lines" id="toc-parallel-lines" class="nav-link" data-scroll-target="#parallel-lines"> <span class="header-section-number">9.6</span> Parallel lines</a>
  <ul class="collapse">
<li><a href="#wisdom" id="toc-wisdom" class="nav-link" data-scroll-target="#wisdom"> <span class="header-section-number">9.6.1</span> Wisdom</a></li>
  <li><a href="#justice" id="toc-justice" class="nav-link" data-scroll-target="#justice"> <span class="header-section-number">9.6.2</span> Justice</a></li>
  <li><a href="#courage" id="toc-courage" class="nav-link" data-scroll-target="#courage"> <span class="header-section-number">9.6.3</span> Courage</a></li>
  <li><a href="#temperance" id="toc-temperance" class="nav-link" data-scroll-target="#temperance"> <span class="header-section-number">9.6.4</span> Temperance</a></li>
  </ul>
</li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"> <span class="header-section-number">9.7</span> Summary</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/PPBDS/primer/edit/main/09-four-parameters.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-four-parameters" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Four Parameters</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="cell">

</div>
<!-- Change Justice section to discuss the math of three possible models you are considering. Predictive or am I doing causal? What is the treatment effect is my question? So, must be causal. Key point: Just because you are using treatment, does not mean that you care it is causal. You may not care. You might only want prediction. So, everything really starts with your question. If you are not asking a causal question, then you don't care if a lefthand side variable has a causal interpretation. You just care if it helps you make better predictions. -->
<!-- Add a question to Temperance and answer it. Probably posterior_epred(). Probably a causation question. Meaning the expected causal effect for a certain sort of person. Which is also a parameter in the regression, which is a good connection to make. MF: Did not have time for this, but I can complete it this week. -->
<!-- Transforming the outcome variable. Give some more thoughts or advice. -->

<!-- Comparing within rows of the Preceptor Table versus across rows, which is all you can do without two potential outcomes. -->
<!-- Also, does not work in logistic. But divide by four rule.  -->
<p>In our haste to make progress — to get all the way through the process of building, interpreting and using models — we have given short shrift to some of the messy details of model building and evaluation. This chapter fills in those lacunae. We will also introduce models with four parameters, including <em>parallel slopes</em> models.</p>
<section id="transforming-variables" class="level2" data-number="9.1"><h2 data-number="9.1" class="anchored" data-anchor-id="transforming-variables">
<span class="header-section-number">9.1</span> Transforming variables</h2>
<!-- Look at "Scaling of predictors and regression coefficients" in RAOS (pg. 183) 

Do we discuss anything in the "Other transformations section" (pg. 195)? This includes square root transformations, idiosyncratic transformations, & using discrete vs continuous predictors. DK: Not square root. Other stuff? Maybe at the end? -->
<p>It is often convenient to transform a predictor variable so that our model makes more sense.</p>
<section id="centering" class="level3" data-number="9.1.1"><h3 data-number="9.1.1" class="anchored" data-anchor-id="centering">
<span class="header-section-number">9.1.1</span> Centering</h3>
<p>Recall our model of <code>income</code> as a function of <code>age</code>.</p>
<p><span class="math display">\[ y_i = \beta_0  + \beta_1 age_i + \epsilon_i\]</span></p>
<p>We fit this using the <code>trains</code> data from <strong>primer.data</strong>. We will also be using a new package, <strong>broom.mixed</strong>, which allows us to tidy regression data for plotting.</p>
<!-- broom.mixed generates a weird warning about TMB was built with Matrix version -->
<!-- 1.3.4 and Current Matrix version is 1.3.3. Not sure what to do, besides turn -->
<!-- it off for now. -->
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">primer.data</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mc-stan.org/rstanarm/">rstanarm</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/bbolker/broom.mixed">broom.mixed</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">income</span> <span class="op">~</span> <span class="va">age</span>, </span>
<span>         data <span class="op">=</span> <span class="va">trains</span>, </span>
<span>         refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>         seed <span class="op">=</span> <span class="fl">9</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">fit_1</span>, detail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Median   MAD_SD  
(Intercept) 103927.5  23785.9
age            887.1    555.9

Auxiliary parameter(s):
      Median  MAD_SD 
sigma 74153.4  4905.9</code></pre>
</div>
</div>
<p>There is nothing wrong with this model. Yet the interpretation of <span class="math inline">\(\beta_0\)</span>, the intercept in the regression, is awkward. It represents the average income for people of age zero. That is useless! There are no people of zero age in our data. And, even if there were, it would be weird to think about such people taking the commuter train into Boston and filling out our survey forms.</p>
<p>It is easy, however, to <em>transform</em> <code>age</code> into a variable which makes the intercept more meaningful. Consider a new variable, <code>c_age</code>, which is <code>age</code> minus the average age in the sample. Using this <strong>c</strong>entered version of age does not change the predictions or residuals in the model, but it does make the intercept easier to interpret.</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trains_2</span> <span class="op">&lt;-</span> <span class="va">trains</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>c_age <span class="op">=</span> <span class="va">age</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_1_c</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">income</span> <span class="op">~</span> <span class="va">c_age</span>, </span>
<span>                    data <span class="op">=</span> <span class="va">trains_2</span>, </span>
<span>                    refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>                    seed <span class="op">=</span> <span class="fl">9</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">fit_1_c</span>, detail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Median   MAD_SD  
(Intercept) 141922.8   6829.9
c_age          915.0    559.2

Auxiliary parameter(s):
      Median  MAD_SD 
sigma 74234.5  4723.3</code></pre>
</div>
</div>
<p>The intercept, 141,923, is the expected income for someone with <code>c_age = 0</code>, i.e., someone of an average age in the data, which is around 42.</p>
</section><section id="scaling" class="level3" data-number="9.1.2"><h3 data-number="9.1.2" class="anchored" data-anchor-id="scaling">
<span class="header-section-number">9.1.2</span> Scaling</h3>
<p>Centering — changing a variable via addition/subtraction — often makes the intercept easier to interpret. Scaling — changing a variable via multiplication/division — often makes it easier to interpret coefficients. The most common scaling method is to divide the variable by its standard deviation.</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trains_3</span> <span class="op">&lt;-</span> <span class="va">trains</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>s_age <span class="op">=</span> <span class="va">age</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_1_s</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">income</span> <span class="op">~</span> <span class="va">s_age</span>, </span>
<span>                    data <span class="op">=</span> <span class="va">trains_3</span>, </span>
<span>                    refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>                    seed <span class="op">=</span> <span class="fl">9</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">fit_1_s</span>, detail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Median   MAD_SD  
(Intercept) 103621.9  25156.0
s_age        10975.5   7115.7

Auxiliary parameter(s):
      Median  MAD_SD 
sigma 74432.7  4950.9</code></pre>
</div>
</div>
<p><code>s_age</code> is age <strong>s</strong>caled by its own standard deviation. A change in one unit of <code>s_age</code> is the same as a change in one standard deviation of the <code>age</code>, which is about 12. The interpretation of <span class="math inline">\(\beta_1\)</span> is now:</p>
<p><em>When comparing two people, one about 1 standard deviation worth of years older than the other, we expect the older person to earn about 11,000 dollars more.</em></p>
<p>But, because we scaled without centering, the intercept is now back to the (nonsensical) meaning of the expected income for people of age 0.</p>
</section><section id="z-scores" class="level3" data-number="9.1.3"><h3 data-number="9.1.3" class="anchored" data-anchor-id="z-scores">
<span class="header-section-number">9.1.3</span> <em>z</em>-scores</h3>
<p>The most common transformation applies both centering and scaling. The base R function <code><a href="https://rdrr.io/r/base/scale.html">scale()</a></code> subtracts the mean and divides by the standard deviation. A variable so transformed is a “<em>z</em>-score,” meaning a variable with a mean of zero and a standard deviation of one. Using <em>z</em>-scores makes interpretation easier, especially when we seek to compare the importance of different predictors.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trains_4</span> <span class="op">&lt;-</span> <span class="va">trains</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>z_age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/scale.html">scale</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_1_z</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">income</span> <span class="op">~</span> <span class="va">z_age</span>, </span>
<span>                    data <span class="op">=</span> <span class="va">trains_4</span>, </span>
<span>                    refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>                    seed <span class="op">=</span> <span class="fl">9</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">fit_1_z</span>, detail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Median   MAD_SD  
(Intercept) 141737.9   6877.0
z_age        11041.8   7035.7

Auxiliary parameter(s):
      Median  MAD_SD 
sigma 74306.7  5154.8</code></pre>
</div>
</div>
<p>The two parameters are easy to interpret after this transformation.</p>
<p><em>The expected income of someone of average age, which is about 42 in this study, is about 142,000 dollars.</em></p>
<p><em>When comparing two individuals who differ in age by one standard deviation, which is about 12 years in this study, the older person is expected to earn about 11,000 dollars more than the younger.</em></p>
<p>Note that, when using <em>z</em>-scores, we would often phrase this comparison in terms of “sigmas.” One person is “one sigma” older than another person means that they are one standard deviation older. This is simple enough, once you get used to it, but also confusing since we are already using the word “sigma” to mean <span class="math inline">\(\sigma\)</span>, the standard deviation of <span class="math inline">\(\epsilon_i\)</span>. Alas, <em>language is something we deal with rather than control.</em> You will hear the same word “sigma” applied to both concepts, even in the same sentence. Determine meaning by context.</p>
</section><section id="taking-logs" class="level3" data-number="9.1.4"><h3 data-number="9.1.4" class="anchored" data-anchor-id="taking-logs">
<span class="header-section-number">9.1.4</span> Taking logs</h3>
<p>It is often helpful to take the log of predictor variables, especially in cases in which their distribution is skewed. You should generally only take the log of variables for which all the values are strictly positive. The log of a negative number is not defined. Consider the number of registered voters (<code>rv13</code>) at each of the polling stations in <code>kenya</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x</span> <span class="op">&lt;-</span> <span class="va">kenya</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">rv13</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span></span>
<span></span>
<span><span class="va">rv_p</span> <span class="op">&lt;-</span> <span class="va">x</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">rv13</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Registered Voters"</span>,</span>
<span>         y <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">log_rv_p</span> <span class="op">&lt;-</span> <span class="va">x</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">rv13</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Log of Registered Voters"</span>,</span>
<span>         y <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/expand_limits.html">expand_limits</a></span><span class="op">(</span>y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">175</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">rv_p</span> <span class="op">+</span> <span class="va">log_rv_p</span> <span class="op">+</span></span>
<span>  <span class="fu">plot_annotation</span><span class="op">(</span>title <span class="op">=</span> <span class="st">'Registered Votes In Kenya Communities'</span>,</span>
<span>                  subtitle <span class="op">=</span> <span class="st">"Taking logs helps us deal with outliers"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-four-parameters_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Most experienced data scientists would use the log of <code>rv13</code> rather than the raw value. Comments:</p>
<ul>
<li><p>We do not know the “true” model. Who is to say that a model using the raw value is right or wrong?</p></li>
<li><p>Check whether or not this choice meaningfully affects the answer to your question. Much of the time, it won’t. That is, our inferences are often fairly “robust” to small changes in the model. If you get the same answer with <code>rv13</code> as from <code>log_rv13</code>, then no one cares which you use.</p></li>
<li><p>Follow the conventions in your field. If everyone does X, then you should probably do X, unless you have a good reason not to. If you do have such a reason, explain it prominently.</p></li>
<li><p>Most professionals, when presented with data distributed like <code>rv13</code>, would take the log. Professionals hate (irrationally?) outliers. Any transformation which makes a distribution look more normal is generally considered a good idea.</p></li>
</ul>
<p>Many of these suggestions apply to every aspect of the modeling process.</p>
<!-- Split out general advice to elsewhere. -->
</section><section id="adding-transformed-terms" class="level3" data-number="9.1.5"><h3 data-number="9.1.5" class="anchored" data-anchor-id="adding-transformed-terms">
<span class="header-section-number">9.1.5</span> Adding transformed terms</h3>
<p>Instead of simply transforming variables, we can add more terms which are transformed versions of a variable. Consider the relation of <code>height</code> to <code>age</code> in <code>nhanes</code>. Let’s start by dropping the missing values.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">no_na_nhanes</span> <span class="op">&lt;-</span> <span class="va">nhanes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">height</span>, <span class="va">age</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Fit and plot a simple linear model:</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nhanes_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">height</span> <span class="op">~</span> <span class="va">age</span>,</span>
<span>                     data <span class="op">=</span> <span class="va">no_na_nhanes</span>,</span>
<span>                     refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>                     seed <span class="op">=</span> <span class="fl">47</span><span class="op">)</span></span>
<span></span>
<span><span class="va">no_na_nhanes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, y <span class="op">=</span> <span class="va">height</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">nhanes_1</span><span class="op">)</span><span class="op">)</span>, </span>
<span>              color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Age and Height"</span>,</span>
<span>         subtitle <span class="op">=</span> <span class="st">"Children are shorter, but a linear fit is poor"</span>,</span>
<span>         x <span class="op">=</span> <span class="st">"Age"</span>,</span>
<span>         y <span class="op">=</span> <span class="st">"Height (cm)"</span>,</span>
<span>         caption <span class="op">=</span> <span class="st">"Data source: NHANES"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-four-parameters_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>That is not a very good model, obviously.</p>
<p>Adding a quadratic term makes it better. (Note the need for <code><a href="https://rdrr.io/r/base/AsIs.html">I()</a></code> in creating the squared term within the <code>formula</code> argument.)</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nhanes_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">height</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">age</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>,</span>
<span>                     data <span class="op">=</span> <span class="va">no_na_nhanes</span>,</span>
<span>                     refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>                     seed <span class="op">=</span> <span class="fl">33</span><span class="op">)</span></span>
<span></span>
<span><span class="va">no_na_nhanes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, y <span class="op">=</span> <span class="va">height</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">nhanes_2</span><span class="op">)</span><span class="op">)</span>, </span>
<span>              color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Age and Height"</span>,</span>
<span>         subtitle <span class="op">=</span> <span class="st">"Quadratic fit is much better, but still poor"</span>,</span>
<span>         x <span class="op">=</span> <span class="st">"Age"</span>,</span>
<span>         y <span class="op">=</span> <span class="st">"Height (cm)"</span>,</span>
<span>         caption <span class="op">=</span> <span class="st">"Data source: NHANES"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-four-parameters_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Still, we have not made use of our background knowledge in creating these variables. We know that people don’t get any taller after age 18 or so. Let’s create variables which capture that break.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nhanes_3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">height</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">age</span> <span class="op">&gt;</span> <span class="fl">18</span>, <span class="fl">18</span>, <span class="va">age</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                     data <span class="op">=</span> <span class="va">no_na_nhanes</span>,</span>
<span>                     refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>                     seed <span class="op">=</span> <span class="fl">23</span><span class="op">)</span></span>
<span></span>
<span><span class="va">no_na_nhanes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, y <span class="op">=</span> <span class="va">height</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">nhanes_3</span><span class="op">)</span><span class="op">)</span>, </span>
<span>              color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Age and Height"</span>,</span>
<span>         subtitle <span class="op">=</span> <span class="st">"Domain knowledge makes for better models"</span>,</span>
<span>         x <span class="op">=</span> <span class="st">"Age"</span>,</span>
<span>         y <span class="op">=</span> <span class="st">"Height (cm)"</span>,</span>
<span>         caption <span class="op">=</span> <span class="st">"Data source: NHANES"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-four-parameters_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The point is that we should not take the variables we receive as <em>given</em>. We are the captains of our souls. We transform variables as needed.</p>
<!-- ### If parameters are unicorns, why bother with transformations? -->
<!-- * standardizing variables. Key advantage is to make the coefficients easier to interpret. Even though the "right" thing to do in looking at models is to use posterior_* to look at model predictions, this takes some time. It is very handy, first pass, to look at all the coefficients and get a sense of which ones are "interesting." Then, focus on those when making newobs tibbles. -->
</section><section id="transforming-the-outcome-variable" class="level3" data-number="9.1.6"><h3 data-number="9.1.6" class="anchored" data-anchor-id="transforming-the-outcome-variable">
<span class="header-section-number">9.1.6</span> Transforming the outcome variable</h3>
<p>Transforming predictor variables is uncontroversial. It does not matter much. Change most continuous predictor variables to <span class="math inline">\(z\)</span>-scores and you won’t go far wrong. Or keep them in their original form, and take care with your interpretations. It’s all good.</p>
<p>Transforming the outcome variable is a much more difficult question. Imagine that we seek to create a model which explains <code>rv13</code> from the <code>kenya</code> tibble. Should we transform it?</p>
<ul>
<li><p>Maybe? There are no right answers. A model with <code>rv13</code> as the outcome variable is different from a model with <code>log(rv13)</code> as the outcome. The two are not directly comparable.</p></li>
<li><p>Much of the same advice with regard to taking logs of predictor variables applies here as well.</p></li>
</ul>
<p>See <span class="citation" data-cites="roas">Gelman, Hill, and Vehtari (<a href="references.html#ref-roas" role="doc-biblioref">2020</a>)</span></p>
</section><section id="interpreting-coefficients" class="level3" data-number="9.1.7"><h3 data-number="9.1.7" class="anchored" data-anchor-id="interpreting-coefficients">
<span class="header-section-number">9.1.7</span> Interpreting coefficients</h3>
<!-- Give example of logistic regression. Intercept of logistic regression is impossible to interpret. -->
<p>When we interpret coefficients, it is important to know the difference between <em>across unit</em> and <em>within unit</em> comparisons. When we compare <em>across unit</em>, meaning comparing Joe and George, we are not looking at a causal relationship. <em>Within unit</em> discussions, where we are comparing Joe under treatment versus Joe under control, are causal. This means that within unit interpretation is only possible in causal models, where we are studying <strong>one unit</strong> under <strong>two conditions</strong>. When we talk about two potential outcomes, we are discussing the same person or unit under two conditions.</p>
<p>To put this in terms of the Preceptor tables, a <em>within unit</em> comparison is looking at one <strong>row</strong> of data: the data for Joe under control and the data for Joe under treatment. We are comparing <strong>one unit</strong>, or (in this case) one person, to itself under two conditions. An <em>across unit</em> comparison is looking at multiple rows of data, with a focus on differences across columns. We are looking at differences <em>without making any causal claims</em>. We are <em>predicting</em>, but we are not implying causation.</p>
<p>The magnitude of the coefficients in linear models are relatively easy to understand. That is not true for logistic regressions. In that case, use the Divide-by-Four rule: Take a logistic regression coefficient (other than the constant term) and divide it by 4 to get an upper bound on the predictive difference corresponding to a unit difference in that variable. All this means is that, when evaluating if a predictor is helpful <em>in a logistic regression only</em>, divide the coefficient by four.</p>
<!-- * Creating new variables, especially by combining different ones into one combined variable. -->
</section></section><section id="selecting-variables" class="level2" data-number="9.2"><h2 data-number="9.2" class="anchored" data-anchor-id="selecting-variables">
<span class="header-section-number">9.2</span> Selecting variables</h2>
<p>How do we decide which variables to include in a model? There is no one right answer to this question.</p>
<section id="general-guidelines-for-selecting-variables" class="level3" data-number="9.2.1"><h3 data-number="9.2.1" class="anchored" data-anchor-id="general-guidelines-for-selecting-variables">
<span class="header-section-number">9.2.1</span> General guidelines for selecting variables</h3>
<p>When deciding which variables to keep or discard in our models, our advice is to keep a variable X if any of the following circumstances apply:</p>
<ul>
<li><p>The variable has a large and well-estimated coefficient. This means, roughly, that the 95% confidence interval excludes zero. “Large” can only be defined in the context of the specific model. Speaking roughly, removing a variable with a large coefficient meaningfully changes the predictions of the model.</p></li>
<li><p>Underlying theory/observation suggests that X has a meaningfully connection to the outcome variable.</p></li>
<li><p>If the variable has a small standard error relative to the size of the coefficient, it is general practice to include it in our model to improve predictions. The rule of thumb is to keep variables for which the estimated coefficient is more than two standard errors away from zero. Some of these variables won’t “matter” much to the model. That is, their coefficients, although well-estimated, are small enough that removing the variable from the model will not affect the model’s predictions very much.</p></li>
<li><p>If the standard error is large relative to the coefficient, i.e., if the magnitude of the coefficient is more than two standard errors from zero, and we find no other reason to include it in our model, we should probably remove the variable from your model.</p></li>
</ul>
<!-- DK: This is confusing. --><ul>
<li><p>The exception to this rule is if the variable is relevant to answering a question which we have. For example, if we want to know if the ending attitude toward immigration differs between men and women, we need to include <code>gender</code> in the model, even if its coefficient is small and closer to zero than two standard errors.</p></li>
<li><p>It is standard in your field to include X in such regressions.</p></li>
<li><p>Your boss/client/reviewer/supervisor wants to include X.</p></li>
</ul>
<p>Let’s use the <code>trains</code> dataset to evaluate how helpful certain variables are to creating an effective model, based on the guidelines above.</p>
</section><section id="variables-in-the-trains-dataset" class="level3" data-number="9.2.2"><h3 data-number="9.2.2" class="anchored" data-anchor-id="variables-in-the-trains-dataset">
<span class="header-section-number">9.2.2</span> Variables in the <code>trains</code> dataset</h3>
<p>To look at our recommendations in practice, let’s focus on the <code>trains</code> dataset. The variables in <code>trains</code> include <code>gender</code>, <code>liberal</code>, <code>party</code>, <code>age</code>, <code>income</code>, <code>att_start</code>, <code>treatment</code>, and <code>att_end</code>. Which variables would be best to include in a model?</p>
</section><section id="att_end-treatment-att_start" class="level3" data-number="9.2.3"><h3 data-number="9.2.3" class="anchored" data-anchor-id="att_end-treatment-att_start">
<span class="header-section-number">9.2.3</span> att_end ~ treatment + att_start</h3>
<p>First, let’s look at a model with a left hand variable, <code>att_end</code>, and two right side variables, <code>treatment</code> and <code>att_start</code>.</p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_1_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">att_end</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">att_start</span>, </span>
<span>                    data <span class="op">=</span> <span class="va">trains</span>, </span>
<span>                    refresh <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_1_model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       gaussian [identity]
 formula:      att_end ~ treatment + att_start
 observations: 115
 predictors:   3
------
                 Median MAD_SD
(Intercept)       2.3    0.4  
treatmentControl -0.9    0.3  
att_start         0.8    0.0  

Auxiliary parameter(s):
      Median MAD_SD
sigma 1.3    0.1   

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<p>How do we decide which variables are useful? First, let’s interpret our coefficients.</p>
<ul>
<li><p>The variable before the tilde, <code>att_end</code>, is our outcome.</p></li>
<li><p>The explanatory variables are <code>treatment</code>, which says whether a commuter relieved treatment or control conditions, and <code>att_start</code>, which measures attitude at the start of the study.</p></li>
<li><p>The 95% confidence interval for <code>att_end</code> is equal to the coefficient– 2– plus or minus two standard errors. This shows the estimate for the <code>att_end</code> where the commuters were under treatment and <strong>were not</strong> in the control group.</p></li>
<li><p>The variable <code>treatmentControl</code> represents the <em>offset</em> in <code>att_end</code> from the estimate for our <code>(Intercept)</code>. This offset is for the group of people that were in the Control group. To find the estimated <code>att_end</code> for those in this group, you must add the median for <code>treatmentControl</code> to the <code>(Intercept)</code> median.</p></li>
<li><p>The variable <code>att_start</code> measures the expected difference in <code>att_end</code> for every one unit increase in <code>att_start</code>.</p></li>
</ul>
<p>The causal effect of the variable <code>treatmentControl</code> is -1. This means that, compared with the predicted <code>att_end</code> for groups under treatment, those in the control group have a predicted attitude that is one entire point lower. As we can see, this is a large and well estimated coefficient. Recall that this means, roughly, that the 95% confidence interval excludes zero. To calculate the 95% confidence interval, we take the coefficient plus or minus two standard errors: -1.3 and -0.5. As we can see, the 95% confidence interval <em>does</em> exclude zero, suggesting that <code>treatment</code> is a worthy variable.</p>
<p>In addition to being meaningful, which is enough to justify inclusion in our model, this variable satisfies a number of other qualifications: - The variable has a small standard error. - The variable is considered an indicator variable, which separates two groups of significance (treatment and control) that we would like to study.</p>
<p>The variable <code>att_start</code>, with a coefficient of 1, is also meaningful. Due to the fact that the <code>MAD_SD</code> value here is 0, we do not need to find the 95% confidence interval to know –intuitively– that this variable has a large and well estimated coefficient.</p>
<p><strong>Conclusion</strong>: keep both variables! <code>treatment</code> and <code>att_start</code> are both significant, as well as satisfying other requirements in our guidelines. They are <em>more</em> than worthy of inclusion in our model.</p>
</section><section id="income-age-liberal" class="level3" data-number="9.2.4"><h3 data-number="9.2.4" class="anchored" data-anchor-id="income-age-liberal">
<span class="header-section-number">9.2.4</span> income ~ age + liberal</h3>
<p>Now, we will look at <code>income</code> as a function of <code>age</code> and <code>liberal</code>, a proxy for political party.</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">income</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">liberal</span>, </span>
<span>                    data <span class="op">=</span> <span class="va">trains</span>, </span>
<span>                    refresh <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       gaussian [identity]
 formula:      income ~ age + liberal
 observations: 115
 predictors:   3
------
            Median   MAD_SD  
(Intercept) 110298.3  23690.0
age           1079.4    534.6
liberalTRUE -32490.6  13481.3

Auxiliary parameter(s):
      Median  MAD_SD 
sigma 72547.0  4894.7

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<p>Great! We have an estimate for income of those who fall into the category of <code>liberalFALSE</code>, as well as data on our right hand side variables of <code>age</code> and <code>liberalTRUE</code>.</p>
<p>First, let’s interpret our coefficients.</p>
<ul>
<li><p>The variable before the tilde, <code>income</code>, is our outcome.</p></li>
<li><p>The explanatory variables are <code>liberal</code>, which has a resulting value of TRUE or FALSE, and <code>age</code>, a numeric variable.</p></li>
<li><p>The <code>(Intercept)</code> is estimating income where <code>liberal == FALSE</code>. Therefore, it is the estimated income for commuters that are not liberals and who have <code>age = 0</code>. The estimate for <code>age</code> is showing the increase in income with every additional year of age.<br></p></li>
<li><p>The estimate for <code>liberalTRUE</code> represents the offset in predicted income for commuters who <em>are</em> liberal. To find the estimate, we must add the coefficient to our <code>(Intercept)</code> value. We see that, on average, liberal commuters make less money.</p></li>
</ul>
<p>It is important to note that we are not looking at a causal relationship for either of these explanatory variables. We are noting the differences between two groups, without considering causality. This is known as an <em>across unit</em> comparison. When we compare <em>across unit</em> we are not looking at a causal relationship.</p>
<p>When comparing <code>liberalTRUE</code> with our <code>(Intercept)</code>, recall that the <code>(Intercept)</code> is calculating income for the case where <code>liberal == FALSE</code>. As we can see, then, the coefficient for <code>liberalTRUE</code>, -32,491, shows that the liberals in our dataset make less on average than non-liberals in our dataset. The coefficient is large relative to the <code>(Intercept)</code> and, with rough mental math, we see that the 95% confidence interval excludes 0. Therefore, <code>liberal</code> is a helpful variable!</p>
<p>The variable <code>age</code>, however, does not appear to have a meaningful impact on our <code>(Intercept)</code>. The coefficient of <code>age</code> is low and the 95% confidence interval <em>does not</em> exclude 0.</p>
<p><strong>Conclusion</strong>: definitely keep <code>liberal</code>! <code>age</code> is less clear. It is really a matter of preference at this point.</p>
</section><section id="liberal-iincome1e05-party" class="level3" data-number="9.2.5"><h3 data-number="9.2.5" class="anchored" data-anchor-id="liberal-iincome1e05-party">
<span class="header-section-number">9.2.5</span> liberal ~ I(income/1e+05) + party</h3>
<p>We will now look at liberal as a function of a transformed <code>income</code> and <code>party</code>. The reason we have transformed <code>income</code> here is due to the fact that, without a transformation, income makes predictions according to <em>very small income disparities</em>. This is not helpful. To enhance the significance of income, we have divided the variable by <span class="math inline">\(100000\)</span>. (Note the need for <code><a href="https://rdrr.io/r/base/AsIs.html">I()</a></code> in creating the income term within the <code>formula</code> argument.)</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">liberal</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">income</span><span class="op">/</span><span class="fl">1e+05</span><span class="op">)</span> <span class="op">+</span> <span class="va">party</span>, </span>
<span>                    data <span class="op">=</span> <span class="va">trains</span>, </span>
<span>                    refresh <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       gaussian [identity]
 formula:      liberal ~ I(income/1e+05) + party
 observations: 115
 predictors:   3
------
                Median MAD_SD
(Intercept)      0.7    0.1  
I(income/1e+05) -0.1    0.1  
partyRepublican -0.5    0.1  

Auxiliary parameter(s):
      Median MAD_SD
sigma 0.5    0.0   

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<p>Recall that, for logistic models, the <code>(Intercept)</code> is nearly impossible to interpret. To evaluate the impact of variables, we will need to use the Divide-by-Four rule. This instructs us to take a logistic regression coefficient (other than the constant term) and divide it by 4 to get an upper bound on the predictive difference corresponding to a unit difference in that variable. All this means is that, when evaluating if a predictor is helpful, <em>in a logistic regression only</em>, to divide the coefficient by four.</p>
<p>For <code>partyRepublican</code>, we take our coefficient, 0, and divide it by 4: -0.125. This is the upper bound on the predictive difference corresponding to a unit difference in this variable. Therefore, we see that <code>partyRepublican</code> is meaningful. We want this variable in our model.</p>
<p>The variable <code>income</code>, however, seems less promising. In addition to the resulting value from the Divide-by-Four rule being low (-0.023), the <code>MAD_SD</code> for income is also equal to the posterior median itself, indicating a standard error which is large relative to the magnitude of the coefficient. Though we may choose to include <code>income</code> for reasons unrelated to its impact in our model, it does not appear to be worthy of inclusion on the basis of predictive value alone.</p>
<p><strong>Conclusion</strong>: the variable <code>party</code> is significant; we will include it in our model. Unless we have a strong reason to include <code>income</code>, we should exclude it.</p>
</section><section id="final-thoughts" class="level3" data-number="9.2.6"><h3 data-number="9.2.6" class="anchored" data-anchor-id="final-thoughts">
<span class="header-section-number">9.2.6</span> Final thoughts</h3>
<p>Now that we have looked at three cases of variables and decided whether they should be included, let’s discuss the concept of selecting variables generally.</p>
<p>The variables we decided to keep and discard are <em>not necessarily the variables you would keep or discard</em>, or the variables that any other data scientist would keep or discard. It is much easier to <strong>keep</strong> a variable than it is to build a case for discarding a variable. Variables are helpful even when not significant, particularly when they are indicator variables which may separate the data into two groups that we want to study.</p>
<p>The process of selecting variables – though we have guidelines – is complicated. There are many reasons to include a variable in a model. The main reasons to exclude a variable are if the variable isn’t significant or if the variable has a large standard error.</p>
<!-- Discuss indicator & index variables prior to explaining guidelines? Not this week! -->
</section></section><section id="comparing-models-in-theory" class="level2" data-number="9.3"><h2 data-number="9.3" class="anchored" data-anchor-id="comparing-models-in-theory">
<span class="header-section-number">9.3</span> Comparing models in theory</h2>
<p>Deciding which variables to include in a model is a subset of the larger question: How do we decide which model, out of the set of possible models, to choose?</p>
<p>Consider two models which explain attitudes to immigration among Boston commuters.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_liberal</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">att_end</span> <span class="op">~</span> <span class="va">liberal</span>,</span>
<span>                  data <span class="op">=</span> <span class="va">trains</span>,</span>
<span>                  refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>                  seed <span class="op">=</span> <span class="fl">42</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">fit_liberal</span>, detail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Median MAD_SD
(Intercept) 10.0    0.3  
liberalTRUE -2.0    0.5  

Auxiliary parameter(s):
      Median MAD_SD
sigma 2.7    0.2   </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_att_start</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">att_end</span> <span class="op">~</span> <span class="va">att_start</span>,</span>
<span>                  data <span class="op">=</span> <span class="va">trains</span>,</span>
<span>                  refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>                  seed <span class="op">=</span> <span class="fl">85</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">fit_att_start</span>, detail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Median MAD_SD
(Intercept) 1.6    0.4   
att_start   0.8    0.0   

Auxiliary parameter(s):
      Median MAD_SD
sigma 1.4    0.1   </code></pre>
</div>
</div>
<p>They both seem like good models! The results make sense. People who are liberal have more liberal attitudes about immigration, so we would expect their <code>att_end</code> scores to be lower. We would also expect people to provide similar answers in two surveys administered a week or two apart. It makes sense that those with higher (more conservative) values for <code>att_start</code> would also have higher values for <code>att_end</code>.</p>
<p>How do we choose between these models?</p>
<section id="better-models-make-better-predictions" class="level3" data-number="9.3.1"><h3 data-number="9.3.1" class="anchored" data-anchor-id="better-models-make-better-predictions">
<span class="header-section-number">9.3.1</span> Better models make better predictions</h3>
<p>The most obvious criteria for comparing models is the accuracy of the predictions. For example, consider the use of <code>liberal</code> to predict <code>att_end</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trains</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>pred_liberal <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">fit_liberal</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">pred_liberal</span>, y <span class="op">=</span> <span class="va">att_end</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.05</span>, height <span class="op">=</span> <span class="fl">0.2</span>, alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="co"># Add a red circle where our predictions are most accurate (where the x and y</span></span>
<span>  <span class="co"># values are the same, which is where our predictions = the true attitudes).</span></span>
<span>  <span class="co"># pch = 1 makes the inside of the point translucent to show the number of</span></span>
<span>  <span class="co"># correct predictions.</span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">8</span>, y <span class="op">=</span> <span class="fl">8</span><span class="op">)</span>, </span>
<span>             size <span class="op">=</span> <span class="fl">20</span>, pch <span class="op">=</span> <span class="fl">1</span>, </span>
<span>             color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">10</span>, y <span class="op">=</span> <span class="fl">10</span><span class="op">)</span>, </span>
<span>             size <span class="op">=</span> <span class="fl">20</span>, pch <span class="op">=</span> <span class="fl">1</span>, </span>
<span>             color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Modeling Attitude Toward Immigration"</span>,</span>
<span>         subtitle <span class="op">=</span> <span class="st">"Liberals are less conservative"</span>,</span>
<span>         x <span class="op">=</span> <span class="st">"Predicted Attitude"</span>,</span>
<span>         y <span class="op">=</span> <span class="st">"True Attitude"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-four-parameters_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<!-- DK: Could put this discussion in fig.cap. Could add some details to the plots to indicate the points that I am talking about. Should create an animation, which brings in new point, forecasts it, and then measures how wrong the model was. -->
<p>Because there are only two possible values for <code>liberal</code> — TRUE and FALSE — there are only two predictions which this model will make: about 10 for <code>liberal == FALSE</code> and about 8 for <code>liberal == TRUE</code>. (The points in the above plot are jittered.) For some individuals, these are perfect predictions. For others, they are poor predictions. the red circles on our plot illustrate the areas where our predictions are equal to true values. As we can see, the model isn’t great at predicting attitude end. (Note the two individuals who are <code>liberal == TRUE</code>, and who the model thinks will have <code>att_end == 8</code>, but who have <code>att_end == 15</code>. The model got them both very, very wrong.)</p>
<p>Consider our second model, using <code>att_start</code> to forecast <code>att_end</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trains</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>pred_liberal <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">fit_att_start</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">pred_liberal</span>, y <span class="op">=</span> <span class="va">att_end</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.05</span>, height <span class="op">=</span> <span class="fl">0.2</span>, alpha <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="co"># Insert red line where our predictions = the truth using geom_abline with an</span></span>
<span>  <span class="co"># intercept, slope, and color.</span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span>intercept <span class="op">=</span> <span class="fl">0</span>, slope <span class="op">=</span> <span class="fl">1</span>, color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Modeling Attitude Toward Immigration"</span>,</span>
<span>         subtitle <span class="op">=</span> <span class="st">"Survey responses are somewhat consistent"</span>,</span>
<span>         x <span class="op">=</span> <span class="st">"Predicted Attitude"</span>,</span>
<span>         y <span class="op">=</span> <span class="st">"True Attitude"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-four-parameters_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Because <code>att_end</code> takes on 13 unique values, the model makes 13 unique predictions. Some of those predictions are perfect! But others are very wrong. The red line shows the points where our predictions match the truth. Note the individual with a predicted <code>att_end</code> of around 9 but with an actual value of <code>15</code>. That is a big miss!</p>
<p>Rather than looking at individual cases, we need to look at the errors for all the predictions. Fortunately, a prediction error is the same thing as a residual, which is easy enough to calculate.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trains</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">att_end</span>, <span class="va">att_start</span>, <span class="va">liberal</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>pred_lib <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">fit_liberal</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>resid_lib <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">fit_liberal</span><span class="op">)</span> <span class="op">-</span> <span class="va">att_end</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>pred_as <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">fit_att_start</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>resid_as <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">fit_att_start</span><span class="op">)</span> <span class="op">-</span> <span class="va">att_end</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 115 × 7
   att_end att_start liberal pred_lib resid_lib pred_as resid_as
     &lt;dbl&gt;     &lt;dbl&gt; &lt;lgl&gt;      &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
 1      11        11 FALSE      10.0    -0.974    10.6    -0.399
 2      10         9 FALSE      10.0     0.0259    8.97   -1.03 
 3       5         3 TRUE        8.02    3.02      4.08   -0.916
 4      11        11 FALSE      10.0    -0.974    10.6    -0.399
 5       5         8 TRUE        8.02    3.02      8.16    3.16 
 6      13        13 FALSE      10.0    -2.97     12.2    -0.769
 7      13        13 FALSE      10.0    -2.97     12.2    -0.769
 8      11        10 FALSE      10.0    -0.974     9.79   -1.21 
 9      12        12 FALSE      10.0    -1.97     11.4    -0.584
10      10         9 FALSE      10.0     0.0259    8.97   -1.03 
# … with 105 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>Let’s look at the square root of the average squared error.</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trains</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">att_end</span>, <span class="va">att_start</span>, <span class="va">liberal</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>lib_err <span class="op">=</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">fit_liberal</span><span class="op">)</span> <span class="op">-</span> <span class="va">att_end</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>as_err <span class="op">=</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">fit_att_start</span><span class="op">)</span> <span class="op">-</span> <span class="va">att_end</span><span class="op">)</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>lib_sigma <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">lib_err</span><span class="op">)</span><span class="op">)</span>,</span>
<span>            as_sigma <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">as_err</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lib_sigma as_sigma
      &lt;dbl&gt;    &lt;dbl&gt;
1      2.68     1.35</code></pre>
</div>
</div>
<p>There are many different measures of the error which we might calculate. The squared difference is most common for historical reasons: it was the mathematically most tractable in the pre-computer age. Having calculated a squared difference for each observation, we can sum them or take their average or take the square root of their average. All produce the same relative ranking, but the last is most popular because it (more or less) corresponds to the estimated <span class="math inline">\(\sigma\)</span> for a linear model. Note how these measures are the same as the ones produced by the Bayesian models created above.</p>
<!-- DK: Could make a movie where we get an X value, we calculate a prediction, we plot it, then we plot the truth, then we measure the distance, then we calculate a squared error. Then speed up the movie, doing it for all the points.  -->
<!-- DK: Could discuss uncertainty in the estimated sigma. But left it out in this draft. -->
<p>Sadly, it is not wise to simply select the model which fits the data best because doing so can be misleading. After all, you are cheating! You are using that very data to select your parameters and then, after using the data once, turning around and “checking” to see how well your model fits the data. It better fit! You used it to pick your parameters! This is the danger of <em>overfitting</em>.</p>
</section><section id="beware-overfitting" class="level3" data-number="9.3.2"><h3 data-number="9.3.2" class="anchored" data-anchor-id="beware-overfitting">
<span class="header-section-number">9.3.2</span> Beware overfitting</h3>
<p>One of the biggest dangers in data science is <em>overfitting</em>, using a model with too many parameters which fits the data we have too well and, therefore, works poorly on data we have yet to see. Consider a simple example with 10 data points.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="09-four-parameters_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What happens when we fit a model with one predictor?</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="09-four-parameters_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>That is a reasonable model. It does not fit the data particularly well, but we certainly believe that higher values of <code>x</code> are associated with higher values of <code>y</code>. A linear fit is not unreasonable.</p>
<!-- DK: Add a discussion about the difference between plotting y versus x, as we do here, and y versus y_hat, which is what we did in the previous section. In fact, show y versus y_hat with this model, right now! -->
<p>But we can also use some of the lessons from above and try a quadratic fit by adding <span class="math inline">\(x^2\)</span> as a predictor.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="09-four-parameters_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Is this a better model? Maybe?</p>
<p>But why stop at adding <span class="math inline">\(x^2\)</span> to the regression? Why not add <span class="math inline">\(x^3\)</span>, <span class="math inline">\(x^4\)</span> and all the way to <span class="math inline">\(x^9\)</span>? When we do so, the fit is much better.</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nine_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">y</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/stats/poly.html">poly</a></span><span class="op">(</span><span class="va">x</span>, <span class="fl">9</span><span class="op">)</span>,</span>
<span>                       data <span class="op">=</span> <span class="va">ovrftng</span><span class="op">)</span></span>
<span></span>
<span><span class="va">newdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">10</span>, by <span class="op">=</span> <span class="fl">0.01</span><span class="op">)</span>,</span>
<span>                  y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">nine_pred</span>, </span>
<span>                              newdata <span class="op">=</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ovrftng</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">newdata</span>, </span>
<span>              <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"`y` as a 9-Degree Polynomial Function of `x`"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">10</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">10</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-four-parameters_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>If the only criteria we cared about was how well the model predicts using the data on which the parameters were estimated, then a model with more parameters will always be better.</em> But that is not what truly matters. What matters is how well the model works on data which was not used to create the model.</p>
<!-- DK: Discuss how this is the perfect model. Plot y versus y_hat. It is a perfect line!  -->
</section><section id="better-models-make-better-predictions-on-new-data" class="level3" data-number="9.3.3"><h3 data-number="9.3.3" class="anchored" data-anchor-id="better-models-make-better-predictions-on-new-data">
<span class="header-section-number">9.3.3</span> Better models make better predictions on new data</h3>
<p>The most sensible way to test a model is to use the model to make predictions and compare those predictions to new data. After fitting the model using <code>stan_glm</code>, we would use <code>posterior_predict</code> to obtain simulations representing the predictive distribution for new cases. For instance, if we were to predict how someone’s attitude changes toward immigration among Boston commuters based on political affiliation, we would want to go out and test our theories on new Boston commuters.</p>
<p>When thinking of generalization to new data, it is important to consider what is relevant new data in the context of the modeling problem. Some models are used to predict the future and, in those cases, we can wait and eventually observe the future and check how good our model is for making predictions. Often models are used to obtain insight to some phenomenon without immediate plan for predictions. This is the case with our Boston commuters example. In such cases, we are also interested whether learned insights from on part of the data generalizes to other parts of the data. For example, if we know how political attitudes informed future immigration stances in <em>Boston commuters</em>, we may want to know if those same conclusions could generalize to train commuters in different locations.</p>
<p>Even if we had detected clear problems with our predictions, this would not necessarily mean that there is anything wrong with the model as fit to the original dataset. However, we would need to understand it further before generalizing to other commuters.</p>
<p>Often, we would like to evaluate and compare models without waiting for new data. One can simply evaluate predictions on the observed data. But since these data have already been used to fit the model parameters, these predictions are optimistic.</p>
<p>In cross validation, part of the data is used to fit the model and the rest of the data—the hold-out set—is used as a proxy for future data. When there is no natural prediction task for future data, we can think of cross validation as a way to assess generalization from one part of the data to another part.</p>
<p>In any form of cross validation, the model is re-fit leaving out one part of the data and then the prediction for the held-out part is evaluated. In the next section, we will look at a type of cross validation called leave-one-out (LOO) cross validation.</p>
</section></section><section id="comparing-models-in-practice" class="level2" data-number="9.4"><h2 data-number="9.4" class="anchored" data-anchor-id="comparing-models-in-practice">
<span class="header-section-number">9.4</span> Comparing models in practice</h2>
<p>To compare models without waiting for new data, we evaluate predictions on the observed data. However, due to the fact that the data has been used to fit the model parameters, our predictions are often optimistic when assessing generalization.</p>
<p>In cross validation, part of the data is used to fit the model, while the rest of the data is used as a proxy for future data. We can think of cross validation as a way to assess generalization from one part of the data to another part. How do we do this?</p>
<!-- In leave-one-out cross validation, we want to perform inferences excluding each data point i, one at a time. In the above expression, excluding that one data point is equivalent to multiplying the posterior distribution by the factor 1/p(yi |θ). The LOO posterior excluding point i is written as p(θ|y−i) = p(θ|y)/p(yi|θ),andtheLOOdistributioniscomputedbytakingtheposteriorsimulations for θ obtained from stan_glm and giving each simulation a weight of 1/p(yi |θ). This set of weighted simulations is used to approximate the predictive distribution of yi , the held-out data point. -->
<p>We can hold out individual observations, called leave-one-out (LOO) cross validation; or groups of observations, called leave-one-group-out cross validation; or use past data to predict future observations, called leave-future-out cross validation. When we perform cross validation, the model is re-fit leaving out one part of the data and then the prediction for the held-out part is evaluated.</p>
<p>For our purposes, we will be performing cross validation using leave-one-out (LOO) cross validation.</p>
<section id="cross-validation-using-loo" class="level3" data-number="9.4.1"><h3 data-number="9.4.1" class="anchored" data-anchor-id="cross-validation-using-loo">
<span class="header-section-number">9.4.1</span> Cross validation using <code>loo()</code>
</h3>
<!-- This is a rough draft. Everything needs to be expanded, but the basics are here. -->
<p>To compare models using leave-one-out (LOO) cross validation, one piece of data is excluded from our model. The model is then re-fit and makes a prediction for the missing piece of data. The difference between the predicted value and the real value is calculated. This process is repeated for every row of data in the dataset.</p>
<p>In essence: <em>One piece of data is excluded from our model, the model is re-fit, the model attempts to predict the value of the missing piece, we compare the true value to the predicted value, and we assess the accuracy of our model’s prediction.</em> This process occurs for each piece of data, allowing us to assess the model’s accuracy in making predictions.</p>
<p>To perform leave-one-out(LOO) cross validation, we will be using the function <code><a href="https://mc-stan.org/loo/reference/loo.html">loo()</a></code> from an R package. This is how we will determine which model is superior for our purposes.</p>
<p>First, we will refamiliarize ourselves with our first model, <code>fit_liberal</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_liberal</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       gaussian [identity]
 formula:      att_end ~ liberal
 observations: 115
 predictors:   2
------
            Median MAD_SD
(Intercept) 10.0    0.3  
liberalTRUE -2.0    0.5  

Auxiliary parameter(s):
      Median MAD_SD
sigma 2.7    0.2   

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<p>Now, we will perform <code><a href="https://mc-stan.org/loo/reference/loo.html">loo()</a></code> on our model and look at the results.</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">loo_liberal</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/loo/reference/loo.html">loo</a></span><span class="op">(</span><span class="va">fit_liberal</span><span class="op">)</span></span>
<span></span>
<span><span class="va">loo_liberal</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Computed from 4000 by 115 log-likelihood matrix

         Estimate   SE
elpd_loo   -279.4  7.5
p_loo         2.9  0.5
looic       558.9 15.0
------
Monte Carlo SE of elpd_loo is 0.0.

All Pareto k estimates are good (k &lt; 0.5).
See help('pareto-k-diagnostic') for details.</code></pre>
</div>
</div>
<p>What does any of this mean?</p>
<ul>
<li>
<code>elpd_loo</code> is the estimated log score along with a standard error representing uncertainty due to using only 115 data points.</li>
<li>
<code>p_loo</code> is the estimated “effective number of parameters” in the model.</li>
<li>
<code>looic</code> is the LOO information criterion, −2 elpd_loo, which we compute for comparability to deviance.</li>
</ul>
<p>For our purposes, we mostly need to focus on <code>elpd_loo</code>. Let’s explain, in more depth, what this information means.</p>
<p>Basically, when we run <code><a href="https://mc-stan.org/loo/reference/loo.html">loo()</a></code>, we are telling R to take a piece of data out of our dataset, re-estimate all parameters, and then predict the value for the missing piece of data. The value for <code>elpd_loo()</code> is based off of how <em>close</em> our estimate was to the truth. Therefore, <code>elpd_loo()</code> values inform us of the effectiveness of our model in predicting data it has not seen before.</p>
<!-- DK: Is this true? I don't think so! The ideal value for `elpd_loo()` is 0, meaning that our predictions are perfect. This is, of course, not going to be the case. We say this to point out that, the closer our value of `elpd_loo` is to 0, the more effective our model performs. -->
<p><strong>The higher our value for <code>elpd_loo</code>, the better our model performs.</strong> This means that, when comparing models, we want to select the model with the higher value for <code>elpd_loo</code>.</p>
<!-- DK: Untrue! Hint: the higher value will be the the value closest to 0, as the results for `elpd_loo()` are negative.  -->
<p>Let’s turn our attention to our second model. To begin, let’s observe the qualities of <code>fit_att_start</code> once again.</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_att_start</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       gaussian [identity]
 formula:      att_end ~ att_start
 observations: 115
 predictors:   2
------
            Median MAD_SD
(Intercept) 1.6    0.4   
att_start   0.8    0.0   

Auxiliary parameter(s):
      Median MAD_SD
sigma 1.4    0.1   

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<p>Great! Now, let’s perform <code><a href="https://mc-stan.org/loo/reference/loo.html">loo()</a></code> on this model.</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">loo_att_start</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/loo/reference/loo.html">loo</a></span><span class="op">(</span><span class="va">fit_att_start</span><span class="op">)</span> </span>
<span></span>
<span><span class="va">loo_att_start</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Computed from 4000 by 115 log-likelihood matrix

         Estimate   SE
elpd_loo   -201.7 12.5
p_loo         4.2  1.8
looic       403.4 25.1
------
Monte Carlo SE of elpd_loo is 0.1.

All Pareto k estimates are good (k &lt; 0.5).
See help('pareto-k-diagnostic') for details.</code></pre>
</div>
</div>
<p>The <code>elpd_loo</code> value for this model is -201.7. This is higher than the <code>elpd_loo</code> for <code>att_liberal</code>, implying that <strong>this</strong> model is superior. However, we can’t see our estimates together. Is there a simpler way to calculate which model is better?</p>
<p>Actually, yes! Using the function <code><a href="https://mc-stan.org/loo/reference/loo_compare.html">loo_compare()</a></code>, we can compare the models directly.</p>
</section><section id="comparing-models-using-loo_compare" class="level3" data-number="9.4.2"><h3 data-number="9.4.2" class="anchored" data-anchor-id="comparing-models-using-loo_compare">
<span class="header-section-number">9.4.2</span> Comparing models using <code>loo_compare()</code>
</h3>
<p>To compare the two models directly, we can use the function <code>loo_compare</code> with our two <code>loo</code> objects created above. This will calculate the difference in <code>elpd_loo()</code> between our models for us, making our job easier:</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://mc-stan.org/loo/reference/loo_compare.html">loo_compare</a></span><span class="op">(</span><span class="va">loo_att_start</span>, <span class="va">loo_liberal</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              elpd_diff se_diff
fit_att_start   0.0       0.0  
fit_liberal   -77.7      12.0  </code></pre>
</div>
</div>
<p>The value for <code>elpd_diff</code> is equal to the difference in <code>elpd_loo</code> between our two models. The<code>se_diff</code> shows that the difference in standard error.</p>
<p>To interpret the results directly, it is important to note that the first row will be the superior model. The values of <code>elpd_diff</code> and <code>att_start</code> will be 0, as these columns show the offset in the estimates compared to the better model. To reiterate: when the better model is compared to itself, those values will be 0. The following rows show the offset in <code>elpd</code> and <code>se</code> values between the less effective model, <code>fit_liberal</code>, and the more effective model, <code>fit_att_start</code>.</p>
<p>The better model is clear: <code>fit_att_start</code>. Therefore, the attitude at the start of the <code>trains</code> study is more significant to predicting final attitude when compared with the variable <code>liberal</code>, which is an analog for political affiliation.</p>
<p>As we have seen, <code>loo_compare</code> is a shortcut for comparing two models. When you are deciding between two models, <code><a href="https://mc-stan.org/loo/reference/loo_compare.html">loo_compare()</a></code> is a great way to simplify your decision.</p>
<p>What do we do when the value of <code><a href="https://mc-stan.org/loo/reference/loo_compare.html">loo_compare()</a></code> is small? As a general practice, differences smaller than four are hard to distinguish from noise. In other words: when <code>elpd_diff</code> is less than 4, there is no advantage to one model over the other.</p>
<!-- ### Selecting the rows -->
</section></section><section id="testing-is-nonsense" class="level2" data-number="9.5"><h2 data-number="9.5" class="anchored" data-anchor-id="testing-is-nonsense">
<span class="header-section-number">9.5</span> Testing is nonsense</h2>
<p>As always, it is important to look at the practices of other professionals and the reasons we may choose not to follow those tactics. For instance, our continued problem with hypothesis testing. In hypothesis testing, we assert a null hypothesis <span class="math inline">\(H_0\)</span> about our data and an alternative hypothesis <span class="math inline">\(H_a\)</span>.</p>
<p>When performing hypothesis testing, we either reject the hypothesis or we do not reject it. The qualifications for rejecting are met if the 95% confidence interval excludes the null hypothesis. If the hypothesis <em>is</em> included in our 95% confidence interval, we do not reject it. In the case of “insignificant” results, with p &gt; 0.5, we also can’t “reject” the null hypothesis. However, this does not mean that we accept it.</p>
<p>The premise of hypothesis testing is to answer a specific question – one that may not even be particularly relevant to our understanding of the world – about our data. So, what are our problems with hypothesis testing? - Rejecting or not rejecting hypotheses doesn’t helps us to answer real questions. - The fact that a difference is not “significant” has no relevance to how we use the posterior to make decisions. - Statistical significance is not equal to <em>practical</em> importance. - There is no reason to <strong>test</strong> when you can summarize by providing the full posterior probability distribution.</p>
</section><section id="parallel-lines" class="level2" data-number="9.6"><h2 data-number="9.6" class="anchored" data-anchor-id="parallel-lines">
<span class="header-section-number">9.6</span> Parallel lines</h2>
<p>To conclude this chapter, we will look at a four parameter model. The model we will use will measure <code>att_end</code> as a function of <code>liberal</code> or <code>att_start</code> or <code>treatment</code> or some combination of these variables.</p>
<!-- DK: We are no longer in the business of telling you what the model should be. There are lots of models we could use! We need to explore the different models and then pick one. -->
<!-- DK: There are three different four parameter models that you could make here. Let's look at all three, pick one and then use it. -->
<section id="wisdom" class="level3" data-number="9.6.1"><h3 data-number="9.6.1" class="anchored" data-anchor-id="wisdom">
<span class="header-section-number">9.6.1</span> Wisdom</h3>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="other/images/Wisdom.jpg" class="img-fluid figure-img" width="1280"></p>
<p></p><figcaption class="figure-caption">Wisdom</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Before making a model which seeks to explain <code>att_end</code>, we should plot it and the variables we think are connected to it:</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">trains</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">att_start</span>, y <span class="op">=</span> <span class="va">att_end</span>, color <span class="op">=</span> <span class="va">liberal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Attitude End Compared with Attitude Start and Liberal"</span>,</span>
<span>       x <span class="op">=</span> <span class="st">"Attitude at Start of Study"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Attitude at End of Study"</span>,</span>
<span>       color <span class="op">=</span> <span class="st">"Liberal?"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-four-parameters_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Is that data believable? Maybe? One could imagine that <code>att_end</code> would be predicted fairly well by <code>att_start</code>. This makes sense for most of our data points, which show not much difference between the attitudes. But what about the great disparities in attitude shown for the individual with a starting attitude of 9 and an ending attitude around 15? In a real data science project, this would require further investigation. For now, we ignore the issue and blithely press on.</p>
<p>Another component of Wisdom is the population. The concept of the “population” is subtle and important. <em>The population is not the set of commuters for which we have data.</em> That is the dataset. The population is the larger — potentially much larger — set of individuals about whom we want to make inferences. <em>The parameters in our models refer to the population, not to the dataset.</em></p>
<p>There are many different populations, each with its own <span class="math inline">\(\mu\)</span>, in which we might be interested. For instance:</p>
<ul>
<li><p>The population of Boston commuters on the specific train and time included in our dataset.</p></li>
<li><p>The population of <em>all</em> Boston commuters.</p></li>
<li><p>The population of commuters in the United States.</p></li>
</ul>
<p>All of these populations are different, so each has a different <span class="math inline">\(\mu\)</span>. Which <span class="math inline">\(\mu\)</span> we are interested in depends on the problem we are trying to solve. It is a judgment call, a matter of Wisdom, as to whether or not that data we have is “close enough” to the population we are interested in to justify making a model.</p>
<p><strong>The major part of Wisdom is deciding what questions you can’t answer because of the data you don’t have.</strong></p>
</section><section id="justice" class="level3" data-number="9.6.2"><h3 data-number="9.6.2" class="anchored" data-anchor-id="justice">
<span class="header-section-number">9.6.2</span> Justice</h3>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="other/images/Justice.jpg" class="img-fluid figure-img" width="960"></p>
<p></p><figcaption class="figure-caption">Justice</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Now that we have considered the connection between our data and the predictions we seek to make, we will need to consider our model.</p>
<p>First: is our model causal or predictive? Recall that our model measures <code>att_end</code> as a function of <code>liberal</code> and <code>att_start</code>. The variables <code>liberal</code> and <code>att_start</code> do not involve a control or treatment dynamic. There is no manipulation with these variables. Given that <strong>there is no causation without manipulation</strong>, this is a predictive model.</p>
<p>We are making inferences about groups of people according to their political affiliation and starting attitude. We are not measuring causality, but we <em>are</em> predicting outcomes.</p>
<p>When creating a parallel slops model, we use the basic equation of a line:</p>
<p><span class="math display">\[y_i = \beta_0  + \beta_1 x_{1,i} + \beta_2 x_{2,i}\]</span></p>
<p>If <span class="math inline">\(y = att\_end\)</span>, <span class="math inline">\(x_1 = att\_start\)</span>, <span class="math inline">\(x\_2 = liberal\)</span>, then the equations are as follows:</p>
<p>If liberal = FALSE:</p>
<p><span class="math display">\[y_i = \beta_0  + \beta_1 x_{1,i}\]</span></p>
<p>Which equates to, in <code>y = b + mx</code> form:</p>
<p><span class="math display">\[y_i = intercept +  \beta_1 att\_start_i\]</span></p>
<p>If liberal = TRUE:</p>
<p><span class="math display">\[y_i = (\beta_0  + \beta_2) + \beta_1 x_{1,i}\]</span></p>
<p>Which equates to, in <code>y = b + mx</code> form:</p>
<p><span class="math display">\[y_i = (intercept + liberal\_true) + \beta_1 att\_start_i\]</span></p>
<!-- DK: Explain, slowly, how we interpret the coefficients, and combinations of the coefficients in the case with treatment and liberal. The intercept is the expected value for someone with FALSE for both treatment and liberal.  The expected value for someone who is both liberal and got the treatment is b_0 + b_1 + b_2. -->
</section><section id="courage" class="level3" data-number="9.6.3"><h3 data-number="9.6.3" class="anchored" data-anchor-id="courage">
<span class="header-section-number">9.6.3</span> Courage</h3>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="other/images/Courage.jpg" class="img-fluid figure-img" width="1024"></p>
<p></p><figcaption class="figure-caption">Courage</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The use of <code>stan_glm</code> is the same as usual. Using <code>stan_glm</code>, we will create our model, <code>fit_1</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">att_end</span> <span class="op">~</span> <span class="va">liberal</span> <span class="op">+</span> <span class="va">att_start</span>,</span>
<span>                  data <span class="op">=</span> <span class="va">trains</span>,</span>
<span>                  refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>                  seed <span class="op">=</span> <span class="fl">42</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       gaussian [identity]
 formula:      att_end ~ liberal + att_start
 observations: 115
 predictors:   3
------
            Median MAD_SD
(Intercept)  1.9    0.5  
liberalTRUE -0.3    0.3  
att_start    0.8    0.0  

Auxiliary parameter(s):
      Median MAD_SD
sigma 1.4    0.1   

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<p>To remind ourselves, recall that the <code>(Intercept)</code> here is representing the <code>att_end</code> value for cases where <code>liberal = FALSE</code> and <code>treatment does not equal Control</code>. The next row, <code>liberalTRUE</code> gives a median value which represents the <em>offset</em> in the prediction compared with the <code>(Intercept)</code>. In other words, the true intercept for cases where <code>liberal = TRUE</code> is represented by <span class="math inline">\((Intercept) + liberalTRUE\)</span>. The value of <code>treatmentControl</code> is the offset in <code>att_end</code> for those in the Control group.</p>
<p>To find our intercepts, we will need to tidy our regression using the <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> function from the <strong>broom.mixed</strong> package. We tidy our data and extract values to create a parallel slopes model. The parallel slopes model allows us to visualize multi-variate Bayesian modeling (i.e.&nbsp;modeling with more than one explanatory variable). That is a complicated way of saying that we will visualize the fitted model created above in a way that allows us to see the intercepts and slopes for two different groups, <code>liberalTRUE</code> and <code>liberalFALSE</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># First, we will tidy the data from our model and select the term and estimate.</span></span>
<span><span class="co"># This allows us to create our regression lines more easily.</span></span>
<span></span>
<span><span class="va">tidy</span> <span class="op">&lt;-</span> <span class="va">fit_1</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">term</span>, <span class="va">estimate</span><span class="op">)</span></span>
<span></span>
<span><span class="va">tidy</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  term        estimate
  &lt;chr&gt;          &lt;dbl&gt;
1 (Intercept)    1.93 
2 liberalTRUE   -0.300
3 att_start      0.799</code></pre>
</div>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Extract and name the columns of our tidy object. By calling tidy$estimate[1],</span></span>
<span><span class="co"># we are telling R to extract the first value from the estimate column in our</span></span>
<span><span class="co"># tidy object.</span></span>
<span></span>
<span><span class="va">intercept</span> <span class="op">&lt;-</span> <span class="va">tidy</span><span class="op">$</span><span class="va">estimate</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="va">liberal_true</span> <span class="op">&lt;-</span> <span class="va">tidy</span><span class="op">$</span><span class="va">estimate</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span>
<span><span class="va">att_start</span> <span class="op">&lt;-</span> <span class="va">tidy</span><span class="op">$</span><span class="va">estimate</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we can define the following terms—- <code>liberal_false_intercept</code> and <code>liberal_false_att_slope</code>; and <code>liberal_true_intercept</code> and <code>liberal_true_att_slope</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Recall that the (Intercept) shows us the estimate for the case where liberal =</span></span>
<span><span class="co"># FALSE. We want to extract the liberal_false_intercept to indicate where the</span></span>
<span><span class="co"># intercept in our visualization should be. The slope for this case, and for the</span></span>
<span><span class="co"># liberal = TRUE case, is att_start.</span></span>
<span></span>
<span><span class="va">liberal_false_intercept</span> <span class="op">&lt;-</span> <span class="va">intercept</span></span>
<span><span class="va">liberal_false_att_slope</span> <span class="op">&lt;-</span> <span class="va">att_start</span></span>
<span></span>
<span><span class="co">#  When wanting the intercept for liberal = TRUE, recall that the estimate for</span></span>
<span><span class="co">#  liberalTRUE is the offset from our (Intercept). Therefore, to know the true</span></span>
<span><span class="co">#  intercept, we must add liberal_true to our intercept.</span></span>
<span></span>
<span><span class="va">liberal_true_intercept</span> <span class="op">&lt;-</span> <span class="va">intercept</span> <span class="op">+</span> <span class="va">liberal_true</span></span>
<span><span class="va">liberal_true_att_slope</span> <span class="op">&lt;-</span> <span class="va">att_start</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>All we’ve done here is extracted the values for our intercepts and slopes, and named them to be separated into two groups. This allows us to create a <code>geom_abline</code> object that takes a unique slope and intercept value, so we can separate the <code>liberalTRUE</code> and <code>liberalFALSE</code> observations.</p>
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># From the dataset trains, use att_start for the x-axis and att_end for</span></span>
<span><span class="co"># the y-axis with color as liberal. This will split our data into two color</span></span>
<span><span class="co"># coordinates (one for liberal = TRUE and one for liberal = FALSE)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">trains</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">att_start</span>, y <span class="op">=</span> <span class="va">att_end</span>, color <span class="op">=</span> <span class="va">liberal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="co"># Use geom_point to show the datapoints. </span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="co"># Create a geom_abline object for the liberal false values. Set the intercept</span></span>
<span>  <span class="co"># equal to our previously created liberal_false_intercept, while setting slope</span></span>
<span>  <span class="co"># equal to our previously created liberal_false_att_slope. The color call is</span></span>
<span>  <span class="co"># for coral, to match the colors used by tidyverse for geom_point().</span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span>intercept <span class="op">=</span> <span class="va">liberal_false_intercept</span>,</span>
<span>              slope <span class="op">=</span> <span class="va">liberal_false_att_slope</span>, </span>
<span>              color <span class="op">=</span> <span class="st">"#F8766D"</span>, </span>
<span>              size <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="co"># Create a geom_abline object for the liberal TRUE values. Set the intercept</span></span>
<span>  <span class="co"># equal to our previously created liberal_true_intercept, while setting slope</span></span>
<span>  <span class="co"># equal to our previously created liberal_true_att_slope. The color call is</span></span>
<span>  <span class="co"># for teal, to match the colors used by tidyverse for geom_point().</span></span>
<span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_abline</a></span><span class="op">(</span>intercept <span class="op">=</span> <span class="va">liberal_true_intercept</span>,</span>
<span>              slope <span class="op">=</span> <span class="va">liberal_true_att_slope</span>,</span>
<span>              color <span class="op">=</span> <span class="st">"#00BFC4"</span>, </span>
<span>              size <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  </span>
<span>  <span class="co"># Add the appropriate titles and axis labels. </span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Parallel Slopes Model"</span>,</span>
<span>       x <span class="op">=</span> <span class="st">"Attitude at Start"</span>, </span>
<span>       y <span class="op">=</span> <span class="st">"Attitude at End"</span>, </span>
<span>       color <span class="op">=</span> <span class="st">"Liberal"</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="09-four-parameters_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This is our parallel slopes model. What we have done, essentially, is created a unique line for <code>liberalTRUE</code> and <code>liberalFALSE</code> to observe the differences in the groups as related to attitude start and attitude end.</p>
<p>As we can see, commuters who are <em>not</em> liberal tend to start with slightly higher values for <code>att_start</code>. Commuters who <em>are</em> liberal tend to have lower starting values for <code>att_start</code>.</p>
<p>Now, what if we want to look at another model? To judge whether we can have a superior model? Let’s create another object, using <code>stan_glm</code>, that looks at <code>att_end</code> as a function of <code>treatment</code> and <code>att_start</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">att_end</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">att_start</span>,</span>
<span>                  data <span class="op">=</span> <span class="va">trains</span>,</span>
<span>                  refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>                  seed <span class="op">=</span> <span class="fl">56</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_glm
 family:       gaussian [identity]
 formula:      att_end ~ treatment + att_start
 observations: 115
 predictors:   3
------
                 Median MAD_SD
(Intercept)       2.4    0.4  
treatmentControl -1.0    0.2  
att_start         0.8    0.0  

Auxiliary parameter(s):
      Median MAD_SD
sigma 1.3    0.1   

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<p>To interpret briefly:</p>
<ul>
<li><p><code>(Intercept)</code> here is representing the <code>att_end</code> value for cases where <code>treatment does not equal Control</code>.</p></li>
<li><p><code>treamtmentControl</code> gives a median value which represents the <em>offset</em> in the prediction compared with the <code>(Intercept)</code>. In other words, the true intercept for cases where <code>treatment = Control</code> is represented by <span class="math inline">\((Intercept) + treatmentControl\)</span>.</p></li>
<li><p><code>att_start</code> represents the slope for both groups representing a unit change.</p></li>
</ul>
<p>An important point here is that <strong>these models are causal</strong>. When including the variable <code>treatment</code>, we have a measured causal effect of a condition. This is different from our prior parallel slopes model, where we were modeling for prediction, not causation.</p>
<!-- DK: A causal model is one in which, at least in theory, one of the righthand side variables could have been manipulated, and when you care about estimating causal effects. If someone just needs to forecast or predict something that, almost always, she is not asking a causal question, so she does not care if the righthand side variables could be manipulated. Is the sunset beautiful if no one is looking at it? Is the model causal if I just want to predict? -->
<p>To see how these models compare in performance, we will perform leave-one-out (LOO) cross validation again.</p>
<div class="cell">
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">L1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/loo/reference/loo.html">loo</a></span><span class="op">(</span><span class="va">fit_1</span><span class="op">)</span></span>
<span></span>
<span><span class="va">L1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Computed from 4000 by 115 log-likelihood matrix

         Estimate   SE
elpd_loo   -202.3 13.1
p_loo         5.5  2.3
looic       404.6 26.1
------
Monte Carlo SE of elpd_loo is 0.1.

Pareto k diagnostic values:
                         Count Pct.    Min. n_eff
(-Inf, 0.5]   (good)     114   99.1%   2531      
 (0.5, 0.7]   (ok)         1    0.9%   157       
   (0.7, 1]   (bad)        0    0.0%   &lt;NA&gt;      
   (1, Inf)   (very bad)   0    0.0%   &lt;NA&gt;      

All Pareto k estimates are ok (k &lt; 0.7).
See help('pareto-k-diagnostic') for details.</code></pre>
</div>
</div>
<p>Perform <code><a href="https://mc-stan.org/loo/reference/loo.html">loo()</a></code> on our second model:</p>
<div class="cell">
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">L2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/loo/reference/loo.html">loo</a></span><span class="op">(</span><span class="va">fit_2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">L2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Computed from 4000 by 115 log-likelihood matrix

         Estimate   SE
elpd_loo   -195.3 12.2
p_loo         5.1  1.8
looic       390.5 24.5
------
Monte Carlo SE of elpd_loo is 0.1.

Pareto k diagnostic values:
                         Count Pct.    Min. n_eff
(-Inf, 0.5]   (good)     114   99.1%   1625      
 (0.5, 0.7]   (ok)         1    0.9%   206       
   (0.7, 1]   (bad)        0    0.0%   &lt;NA&gt;      
   (1, Inf)   (very bad)   0    0.0%   &lt;NA&gt;      

All Pareto k estimates are ok (k &lt; 0.7).
See help('pareto-k-diagnostic') for details.</code></pre>
</div>
</div>
<p>Recall that the relevant data is the data from <code>elpd_loo</code>. The estimates for <code>elpd_loo</code> vary quite a bit. Recall that the superior model will have a value of <code>elpd_loo()</code> that is closer to 0. The standard error (SE) for these models also differs some. To compare these directly, we will use <code>loo_compare</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://mc-stan.org/loo/reference/loo_compare.html">loo_compare</a></span><span class="op">(</span><span class="va">L1</span>, <span class="va">L2</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      elpd_diff se_diff
fit_2  0.0       0.0   
fit_1 -7.0       3.8   </code></pre>
</div>
</div>
<p>Recall that, with <code><a href="https://mc-stan.org/loo/reference/loo_compare.html">loo_compare()</a></code>, the resulting data shows the superior model first, with values of 0 for <code>elpd_diff</code> and <code>se_diff</code>, since it compares the models to the best option. The values of <code>elpd_diff</code> and <code>se_diff</code> for <code>fit_1</code> show the difference in the models. As we can see, <code>fit_2</code>, the model which looks at <code>treatment</code> + <code>att_start</code>, is better.</p>
<p>But how certain can we be that it is better? Note that the difference between the two models is not quite two standard errors. So, there is a reasonable possibility that the difference is due to chance.</p>
<!-- DK: Say more here! -->
</section><section id="temperance" class="level3" data-number="9.6.4"><h3 data-number="9.6.4" class="anchored" data-anchor-id="temperance">
<span class="header-section-number">9.6.4</span> Temperance</h3>
<p>What we really care about is data we haven’t seen yet, mostly data from tomorrow. But what if the world changes, as it always does? If it doesn’t change much, maybe we are OK. If it changes a lot, then what good will our model be? In general, the world changes some. That means that are forecasts are more uncertain that a naive use of our model might suggest. Having created (and checked) a model, we now use the model to answer questions. Models are made for use, not for beauty. The world confronts us. Make decisions we must. Our decisions will be better ones if we use high quality models to help make them.</p>
<p>Preceptor’s Posterior is the posterior you would calculate if all the assumptions you made under Wisdom and Justice were correct. Sadly, they never are! So, you can never know Preceptor’s Posterior. Our posterior will, we hope, be a close-ish approximation of Preceptor’s Posterior.</p>
<!-- Discuss the difference in our estimated treatment effect for this chapter and the model in chapter 8 and in the model we did not use here. There is no truth! Which is why we need to be humble and cautious when using our posterior. Be Temperate! -->
<!-- att_end ~ liberal + att_start. Same thing as chapters before. Show graphic of parallel lines. Cardinal virtues as always. And, extra, at the end we can use loo_compare to see if this model is better than simpler model of att_end ~ att_start. -->
<!-- What is the expected difference in attitude end between a liberal with start 6 and a non liberal with start 10? Do that by hand with posterior_epred. Then show how you can get a similar answer just by interpreting coefficents. -->
</section></section><section id="summary" class="level2" data-number="9.7"><h2 data-number="9.7" class="anchored" data-anchor-id="summary">
<span class="header-section-number">9.7</span> Summary</h2>
<p>In this chapter, we covered a number of topics important to effectively creating models.</p>
<p><em>Key commands</em>: - Create a model using <code><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm()</a></code>. - After creating a model, we can use <code><a href="https://mc-stan.org/loo/reference/loo.html">loo()</a></code> to perform leave-one-out cross validation. This assesses how effectively our model makes predictions for data it has not seen yet. - The command <code><a href="https://mc-stan.org/loo/reference/loo_compare.html">loo_compare()</a></code> allows us to compare two models, to see which one performs better in leave-one-out cross validation. The superior model makes better predictions.</p>
<p><em>Remember</em>: - We can transform variables – through centering, scaling, taking logs, etc. – to make them more sensible. Consider using a transformation if the intercept is awkward. For instance, if the intercept for <code>age</code> represents the estimate for people of age zero, we might consider transforming <code>age</code> to be easier to interpret. - When selecting variables to include in our model, follow this rule: keep it if the variable has a large and well-estimated coefficient. This means that the 95% confidence interval excludes zero. Speaking roughly, removing a variable with a large coefficient meaningfully changes the predictions of the model. - When we compare <em>across unit</em>, meaning comparing Joe and George, we are not looking at a causal relationship. <em>Within unit</em> discussions, where we are comparing Joe under treatment versus Joe under control, are causal. This means that within unit interpretation is only possible in causal models, where we are studying <strong>one unit</strong> under <strong>two conditions</strong>. - When we talk about two potential outcomes, we are discussing the same person or unit under two conditions.</p>
<div class="cell">

</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-roas" class="csl-entry" role="doc-biblioentry">
Gelman, Andrew, Jennifer Hill, and Aki Vehtari. 2020. <em>Regression and Other Stories</em>. Analytical Methods for Social Research. Cambridge University Press. <a href="https://doi.org/10.1017/9781139161879">https://doi.org/10.1017/9781139161879</a>.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./08-three-parameters.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Three Parameters</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10-five-parameters.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Five Parameters</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>